micronaut:
    io:
        watch:
            paths: src/main
            enabled: true
    application:
        name: account-casino
    server:
        host: localhost
        port: 8091
        cors:
            enabled: true
            configurations:
                web:
                    allowedOrigins:
                        - http://localhost:4040
                    exposedHeaders:
                        - Content-Type
                        - Authorization
                        - Date
#        multipart:
#            enabled: true --> for uploading pictures etc or sending them in http
        log-handled-exceptions: true
#    router:
#        static-resources:
#            default:
#                paths: "classpath:static"
#                mapping: "/**" # maps root path to static resource -> localhost/stat.jpg
    security:
        authentication: bearer
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: 'MeinGeheimnisbleitGeheimMeinGeheMeinGeheimnisbleitGeheimMeinGehe'
                            jws-algorithm: HS256
                            base64: true
                        validation:
                            secret: 'MeinGeheimnisbleitGeheimMeinGeheMeinGeheimnisbleitGeheimMeinGehe'
            propagation:
                header:
                    enabled: true
                    header-name: "Authorization"
                    prefix: "Bearer "
                enabled: true
                service-id-regex: "gateway-casino|cardgame-casino|data-casino"
        endpoints:
            login:
                enabled: false #CustomLoginController
            oauth:
                enabled: true
                path: '/oauth/access_token'
                get-allowed: true
        #                enabled: true
#                path: '/oauth/access_token'

        redirect:
#        endpoints:
#            login:
#                path:
#            login-success: http://localhost:8092
        http:
            services:
                gateway-casino:
                    urls:
                        - "http://localhost:4040"
                cardgame-casino:
                    urls:
                        - "http://localhost:8092"
                data-casino:
                    urls:
                        - 'http:localhost:8093'
endpoints:
    env:
        enabled: true
        sensitive: false
    loggers:
        enabled: true
        sensitive: false
    beans:
        enabled: true
        sensitive: false
    info:
        enabled: true
        sensitive: false
    routes:
        enabled: true
        sensitive: false
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS
    metrics:
        enabled: true
        sensitive: false
    flyway:
        enabled: true
        sensitive: false


jackson:
    module-scan: true
    bean-introspection-module: true
    locale: de_DE
    time-zone: Europe/Berlin
vertx:
    mysql:
        client:
            port: 3306
            host: localhost
            database: casino_db
            user: root
            password: dev
            max-size: 5
consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
tracing:
    jaeger:
        enabled: true
        sampler:
            propability: 1
        sender:
            agent-port: 6831

