micronaut:
    io:
        watch:
            paths: src/main
            enabled: true
    application:
        name: gateway-casino
    server:
        host: localhost
        port: 4040
        cors:
        multipart:
            enabled: true
        log-handled-exceptions: true
    security:
        authentication: bearer
        endpoints:
            login:
                enabled: false #LoginController custom implementation
            oauth:
                enabled: false
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: 'MeinGeheimnisbleitGeheimMeinGeheMeinGeheimnisbleitGeheimMeinGehe'
                            jws-algorithm: HS256
                            base64: true
                        validation:
                            secret: 'MeinGeheimnisbleitGeheimMeinGeheMeinGeheimnisbleitGeheimMeinGehe'
            propagation:
                enabled: true
                header:
                    enabled: true
                    header-name: "Authorization"
                    prefix: "Bearer "
                service-id-regex: "account-casino|cardgame-casino"
    http:
        services:
            account-casino:
                urls:
                    - "http://localhost:8091"
            cardgame-casino:
                urls:
                    - "http://localhost:8092"
endpoints:
    env:
        enabled: true
        sensitive: false
    loggers:
        enabled: true
        sensitive: false
    beans:
        enabled: true
        sensitive: false
    info:
        enabled: true
        sensitive: false
    routes:
        enabled: true
        sensitive: false
#        details-visible: ANONYMOUS
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS
jackson:
    module-scan: true
    bean-introspection-module: true
    time-zone: Europe/Berlin
consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
tracing:
    jaeger:
        enabled: true
        sampler:
            propability: 1
        sender:
            agent-port: 6831