version: "3"

services:
    mysql:
        container_name: mysql-db
        image: library/mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_USER: root
            MYSQL_DATABASE: casino_db
        ports:
            - "3306:3306"
        volumes:
            - ./db/db.mySqlDB.sql:/docker-entrypoint-initdb.d/mySqlDB.sql
            - ./db/db.mySqlDB-volume:/var/lib/mysql
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=cardgameDB
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=dev
        volumes:
        - ./db/db.mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        - ./db/db.mongo-volume:/data/db
        ports:
        - "27017:27017"
        - "27018:27018"
        - "27019:27019"
    redis:
        image: redis:6.0.1-alpine
        container_name: redis_db
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./db/db.redis:/data
            - ./docker/data/redis:/redis/data
    consul:
        image: bitnami/consul:1.9.0
        container_name: casino-consul-discovery
        restart: always
        ports:
            - "8300:8300"
            - "8301:8301"
            - "8301:8301/udp"
            - "8500:8500"
            - "8600:8600"
            - "8600:8600/udp"
        volumes:
        - ./docker/consul_data:/bitnami
    jaeger-all-in-one:
        image: jaegertracing/all-in-one:latest
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        restart: always
        ports:
            - 5775:5775/udp
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686
            - 14268:14268
            - 9411:9411
#    jaeger-collector:
#        container_name: casino-jaeger-collector
#        image: jaegertracing/jaeger-collector:latest
#        command: [ "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411" ]
#        ports:
#            - "14269:14269"
#            - "14268:14268"
#            - "14267:14267"
#            - "9411:9411"
#            - "14250:14250"
#        restart: on-failure
#        depends_on:
#            - cassandra-schema
#        environment:
#            - LOG_LEVEL=debug
#            - SPAN_STORAGE_TYPE=cassandra
#
#    jaeger-query:
#        container_name: casino-jaeger-query
#        image: jaegertracing/jaeger-query:latest
#        command: [ "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra" ]
#        ports:
#            - "16686:16686"
#            - "16687:16687"
#        restart: on-failure
#        depends_on:
#            - cassandra-schema
#        environment:
#            - LOG_LEVEL=debug
#            - JAEGER_AGENT_HOST=jaeger-collector
#            - JAEGER_AGENT_PORT=6831
#
#    jaeger-agent:
#        container_name: casino-jaeger-agent
#        image: jaegertracing/jaeger-agent:latest
#        command: [ "--reporter.grpc.host-port=jaeger-collector:14250" ]
#        ports:
#            - "5775:5775/udp"
#            - "6831:6831/udp"
#            - "6832:6832/udp"
#            - "5778:5778"
#        restart: on-failure
#        depends_on:
#            - jaeger-collector
#        environment:
#            - LOG_LEVEL=debug
#
#    cassandra:
#        container_name: casino-cassandra
#        image: library/cassandra:latest
#    cassandra-schema:
#        container_name: casino-cassandra-schema
#        image: jaegertracing/jaeger-cassandra-schema:latest
#        depends_on:
#            - cassandra



